### PR TITLE
Added method to changing Decimal Point title

### PR DESCRIPTION
**Pull request by kioltk**
Now you just can type `keyboard.decimalPointKeyTitle = @"+";` for phone typing or anything

### CODE REVIEW

**Comment by matmartinez** [comment]
Hi @kioltk,

This key should always be the decimal separator for the locale. Sorry, no can do.

Matías.

**Comment by kioltk** [comment]
How should I use this keyboard for entering phone number so?

**Comment by matmartinez** [comment]
@kioltk hey there! The simple answer is that you shouldn't. There's a number keypad for phone numbers built into UIKit. Check out `UIKeyboardType.DecimalPad`.

Thanks.

**Comment by kioltk** [comment]
Built-in keyboards are not customizable, however your keyboard can be more extendable than simple decimals' pad.
However why do you mention the .DecimalPad? There is no dependencies in this library with .DecimalPad and can be used for any purpose.

**Comment by matmartinez** [comment]
The `UIKeyboardType` enum is part of UIKit (iOS), not this library.

Please learn more about this in the documentation or [this handy blog post](http://www.globalnerdy.com/2015/05/04/ios-8s-built-in-virtual-keyboards-on-the-iphone-a-visual-catalog/#PhonePad).

I encourage you to use `UIKeyboardType.PhonePad` if you need a phone keyboard.

**Pull request closed without merging**
