### PR TITLE
Add Done button customization

### PR DESCRIPTION
**Pull request by brightsider**

### CODE REVIEW

**Comment by matmartinez** [comment]
Hi there, brightsider! Thanks for coding this. 

I like your idea, but I don't think it's a good idea to let users provide `UIColor` instances. It would be more appropriate to provide button "styles", it's easy, quick and virtually eliminates the risk of weird color combinations :) I'll implement this in the near future.

Let me know what you think.

**Comment by matmartinez** [comment]
Support to do this was added on **MMNumberKeyboard 0.1.5** using "styles" instead of colors. I'm closing this now, thanks.

**Comment by rigobertomolina** [comment]
I really think this pull request should of been accepted. I'm totally using this is my code. Sometimes developers have a specific theme color and they would like to configure that around the app.

**Comment by rigobertomolina** [comment]
Lmfao never mind then. I thought this changed the button's background. 😂 Please keep this closed.

**Comment by rigobertomolina** [comment]
***This*** is what I wanted.
screen shot 2016-07-03 at 5 28 28 am

**Comment by matmartinez** [comment]
Hi rigobertomolina,

The "Done" key's background color is inherited from the tint color of its parent view, in the same way UIButtons do since iOS 7. 

The tint color for input views matches the color of system keyboards; it was made this way by Apple so your keyboard looks in context and consistent. 

Remember that system keyboards aren't customized by iOS with your application's tint color. 

If you still want to use a custom tint color, just like with any other UIView, set it manually on the MMNumberKeyboard instance with the tint color property.

**Pull request closed without merging**
